name:
  en: "Web and desktop applications"
  ar: "تطبيقات الويب وسطح المكتب"
keywords:
  - "Svelte"
  - "SvelteKit"
  - "Tauri"
  - "React"
  - "SolidJS"
  - "Tailwind CSS"
  - "Node.js"
  - "HTML"
  - "CSS"
  - "ASP.NET MVC"
  - "Entity Framework"
order: 2
